FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /usr/share/nginx/front

RUN mkdir -p /usr/share/nginx/admin

COPY build /usr/share/nginx/front

COPY ../blog-admin-by-react/build /usr/share/nginx/admin

EXPOSE 80
